services:
  top-of-mind-beromfabriken:
    build: .
    container_name: top-of-mind-beromfabriken
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.top-of-mind-beromfabriken.rule=Host(`top-of-mind-beromfabriken.labbytan.se`)"
      - "traefik.http.routers.top-of-mind-beromfabriken.entrypoints=websecure"
      - "traefik.http.routers.top-of-mind-beromfabriken.tls.certresolver=myresolver"
      - "traefik.http.services.top-of-mind-beromfabriken.loadbalancer.server.port=8501"

networks:
  web:
    external: true